name: Setup environment
description: Setup environment for running workflows.
inputs:
  build-log-output-file:
    description: 'File to store the build log to.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Compile base version of the static and shared libraries
      shell: sh
      run: make release 2>build_log
    - name: Cache file with warnings
      uses: actions/cache@v3
      with:
        path: ./build_log
        key: build-log-${{ inputs.build-log-output-file }}-${{ runner.os }}-${{ github.sha }}
